export const INIT_QUESTIONS = [
  "Trong lúc yêu nhau, anh/em thích được khen ngợi vì điều gì?",
  "Những điểm xấu nào mà anh/em muốn được thông cảm?",
  "Những điểm xấu nào mà anh/em không thể chấp nhận được?",
  "Nếu được gặp lại chính mình trước lúc quen nhau, anh/em sẽ nói gì về mối quan hệ này?",
  "Điều gì về anh mà anh nghĩ em đã hiểu sai rồi?",
  "Anh sẽ xin lỗi em vì chuyện gì trong quá khứ?",
  "Anh nghĩ em nên xin lỗi anh vì chuyện gì trong quá khứ?",
  "Khi nào thì anh thấy thất vọng vì em?",
  "Anh muốn em thay đổi điều gì?",
  "Em nghĩ anh nên thay đổi điều gì để mối quan hệ này tốt hơn?",
  "Nếu bạn liên kết tình yêu với một hình ảnh, nó sẽ là gì?",
  "Theo bạn, 3 yếu tố chính để tạo nên một mối quan hệ là gì?",
  "Những đặc điểm mà người bạn đời lý tưởng của bạn nên có là gì?",
  "Tuy nhiên, những đặc điểm mà người bạn đời lý tưởng của bạn hoàn toàn không nên có là gì?",
  "Bạn thường cư xử như thế nào khi cãi nhau? Và sau đó?",
  "Điều đầu tiên bạn nhìn vào một người là gì?",
  "Điều đầu tiên bạn nhận thấy ở tôi là gì?",
  "Sống thử hay kết hôn?",
  "Bạn sẽ quản lý việc phân chia công việc gia đình như thế nào?",
  "Bạn muốn tổ chức đám cưới của mình như thế nào?",
  "Bạn đã có bao nhiêu mối quan hệ trước tôi?",
  "Làm thế nào và tại sao các mối quan hệ trước đây của bạn kết thúc?",
  "Bạn đang ở trong mối quan hệ nào với người yêu cũ?",
  "Giá trị tốt nhất của tôi là gì?",
  "Điều gì làm bạn khó chịu nhất về tôi?",
  "Bạn muốn tôi giỏi hơn ở điểm nào và tại sao? Còn bạn?",
  "Khi nào bạn nhận ra bạn muốn ở bên tôi?",
  "Tôi phải làm gì để bạn thực sự hạnh phúc?",
  "Nếu bạn gặp khó khăn, bạn sẽ làm gì để tôi cảm thấy dễ chịu?",
  "Chúng ta nên làm gì để làm cho mối quan hệ của chúng ta tốt hơn?",
  "Nếu bạn phải dành một bài hát cho chính tôi, đó sẽ là gì?",
  "Điều điên rồ nhất mà bạn đã làm vì tình yêu là gì?",
  "Kỉ niệm đẹp nhất liên quan đến tuổi thơ của bạn là gì?",
  "Kỉ niệm xấu nhất liên quan đến tuổi thơ của bạn là gì?",
  "Bạn là đứa trẻ như thế nào?",
  "Bạn giống mẹ và giống bố như thế nào?",
  "Bạn muốn khác bố mẹ mình như thế nào?",
  "Bạn sẽ làm gì khác hơn nếu bạn ở trong hoàn cảnh của cha mẹ mình?",
  "Bạn muốn sống gần hay xa cha mẹ của bạn?",
  "Bạn có muốn sống gần gia đình tôi không?",
  "Nếu bố mẹ bạn không thích tôi, bạn sẽ làm gì?",
  "Nếu gia đình tôi không hoàn toàn tin vào mối quan hệ của chú,ng tôi, bạn sẽ làm gì để được chấp nhận?",
  "Điều thất vọng lớn nhất mà bạn đã cho bố mẹ và họ đã cho bạn là gì?",
  "Bạn đã đối phó với khoảng thời gian đặc biệt khó khăn trong quá khứ như thế nào?",
  "Bạn có cảm thấy ghen tị nếu tôi nhìn một người khác?",
  "Nó có làm phiền bạn không nếu tôi nói chuyện với bạn bè của bạn?",
  "Bạn sẽ làm gì nếu người khác đánh tôi?",
  "Nếu tôi hỏi bạn, bạn có để tôi nhìn vào điện thoại của bạn không?",
  "Bạn nghĩ gì về tình bạn giữa nam và nữ?",
  "Bạn có thấy phiền nếu tôi nói về những người bạn đời cũ của mình không?",
  "Bạn sẽ cảm thấy gì nếu tôi vẫn giữ mối quan hệ tốt với người yêu cũ của mình?",
  "Nếu bạn có cơ hội quan hệ tình dục với một người khác, mà không bị bắt, bạn có làm điều đó không?",
  "Nếu em lừa dối anh, anh có nói cho em biết không?",
  "Nếu tôi phản bội bạn, bạn có muốn biết không?",
  "Bạn có thể tha thứ cho sự phản bội?",
  "Nếu anh bỏ em đi vì người khác, em sẽ phản ứng như thế nào?",
  "Bạn sẽ làm gì để được tha thứ cho sự phản bội?",
  "Bạn sẽ cư xử như thế nào nếu tôi nói với bạn rằng bạn bị thu hút bởi một người khác, mà chưa làm gì với điều đó?",
  " Tình dục quan trọng như thế nào đối với bạn trong một mối quan hệ?",
  "Làm thế nào nó khiến bạn nghe về tình dục một cách cởi mở với bạn đời của mình?",
  "Theo quy định, bạn nên quan hệ tình dục bao lâu một lần?",
  "Bạn có thể kéo dài bao lâu mà không quan hệ tình dục?",
  "Tưởng tượng lớn nhất của bạn là gì?",
  "Vị trí yêu thích của bạn là gì?",
  "Bạn thích được chạm vào chỗ nào?",
  "Nơi kỳ lạ nhất mà bạn từng làm tình là gì?",
  "Màn dạo đầu quan trọng như thế nào đối với bạn?",
  "Kỉ niệm xấu hổ nhất mà bạn có liên quan đến tình dục là gì?",
  "Lần đầu tiên của bạn với ai và như thế nào? Bạn bao nhiêu tuổi?",
  "Điều gì khiến bạn hứng thú nhất?",
  "Điều gì làm cho ham muốn của bạn đột ngột giảm xuống?",
  "Bạn có muốn thử nghiệm với đồ chơi tình dục trên giường không?",
  "Bạn có muốn có con trong tương lai không?",
  "Nếu vậy, bạn muốn có bao nhiêu con?",
  "Bạn muốn truyền lại những giá trị nào cho con cái?",
  "Nếu bạn là người vô sinh và bạn muốn có con, bạn sẽ cư xử như thế nào?",
  "Bạn muốn dạy con điều gì?",
  "Bạn sẽ thiết lập việc giáo dục con cái như thế nào?",
  "Điều khiến bạn sợ nhất khi có con là gì?",
  "Bạn nghĩ việc trở thành cha mẹ ở độ tuổi nào là đúng?",
  "Theo bạn, sai lầm lớn mà cha mẹ có thể mắc phải là gì?",
  "Điều gì bạn sẽ không bao giờ muốn con bạn nói với bạn?",
  "Bạn thấy bản thân mình như thế nào, đang làm việc nói từ bây giờ đến 10 năm nữa?",
  "Công việc quan trọng như thế nào trong cuộc sống của bạn?",
  "Bạn có bao giờ hy sinh gia đình vì công việc?",
  "Bạn thà nhận được công việc mà bạn hằng mơ ước hay tìm thấy tình yêu đích thực?",
  "Nếu bạn chuyển đi vì lý do công việc, bạn có chấp nhận một mối quan hệ xa?",
  "Bạn có bỏ việc để chuyển đến nơi khác với đối tác của mình không?",
  "Bạn sẽ cảm thấy thế nào nếu đối tác của bạn kiếm được nhiều hơn bạn?",
  "Bạn thường trải qua những ngày cuối tuần như thế nào?",
  "Bạn thích làm gì trong thời gian rảnh?",
  "Bạn là người thích thể thao? Nếu vậy, bạn thích môn thể thao nào hơn?",
  "Bạn thích đi du lịch?",
  "Nếu chúng ta có thể rời đi vào ngày mai, bạn muốn đi đâu?",
  "Bạn thích ăn ở nhà hay ở nhà hàng?",
  "Kỳ nghỉ lý tưởng của bạn là gì? Thành phố của nghệ thuật hay biển?",
  "Sở thích của bạn là gì?",
  "Bạn sẽ làm những hoạt động gì với tư cách là một cặp đôi với tôi?",
  "Nếu tôi yêu cầu bạn làm điều gì đó với tôi / cho tôi khiến bạn vô cùng khó chịu, bạn có chấp nhận không?",
  "Điều gì bạn có thể tuyệt đối không từ bỏ?",
  "Bạn đã sẵn sàng để làm những điều mới hay bạn thích thói quen hơn?",
  "Bạn sẽ đi gì đến một hòn đảo hoang?",
  "Đêm chiếu phim và pizza hay hiphop never die =))?",
  "Bạn tưởng tượng những ngày của chúng ta sau khi nghỉ hưu như thế nào?",
  "Nếu tôi bị ốm, bạn sẽ chăm sóc tôi như thế nào?",
  "Bạn tưởng tượng thế nào về quan hệ tình dục sau một độ tuổi nhất định?",
  "Nếu được lựa chọn, bạn muốn sống tuổi già ở đâu?",
  "Theo bạn, bí quyết nào để không cảm thấy mệt mỏi sau cuộc sống chung?",
];
